version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env.example
    # environment:
    #   - PORT=5000
    #   - BASE_URL=http://localhost
    #   - MONGODB_URI=mongodb://mongo:27017/merndat
    #   - NODE_ENV=production
    #   - NODE_NO_WARNINGS=1
    #   - TOKEN_EXPIRATION=2h
    #   - TOKEN_SECRET=woooahItsASeCrEt
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"